#@data/values
---
AVI_CLOUD_NAME: "Default-Cloud"
AVI_SERVICE_ENGINE: "Default-Group"
AVI_CONTROLLER: 10.161.150.145
AVI_NAMESPACE: "tanzu-system-networking"
AVI_AKO_IMAGE: harbor-pks.vmware.com/tkgextensions/tkg-networking/ako
AVI_AKO_IMAGE_TAG: master-dad9e53
AVI_DISABLE_INGRESS_CLASS: true
AVI_DATA_NETWORK: "VM Network"
AVI_DATA_NETWORK_CIDR: 10.161.136.0/24
AVI_DATA_NETWORK_IP_POOL_START: 10.161.136.31
AVI_DATA_NETWORK_IP_POOL_END: 10.161.136.42
AVI_USERNAME: "admin"
AVI_PASSWORD: "admin!23"
AVI_CA_DATA: |
  -----BEGIN CERTIFICATE-----
  MIIF+DCCA+CgAwIBAgIBATANBgkqhkiG9w0BAQsFADBgMQswCQYDVQQGEwJVUzET
  MBEGA1UECAwKQ2FsaWZvcm5pYTEUMBIGA1UEBwwLU2FudGEgQ2xhcmExEzARBgNV
  BAoMCkNvbnRyb2xsZXIxETAPBgNVBAMMCGNhLmxvY2FsMB4XDTcwMDEwMTAwMDAw
  MFoXDTMwMTIxNDIyNDAxMlowYDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlm
  b3JuaWExFDASBgNVBAcMC1NhbnRhIENsYXJhMRMwEQYDVQQKDApDb250cm9sbGVy
  MREwDwYDVQQDDAhjYS5sb2NhbDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
  ggIBANwQCd5kOaWNdRT1ra+7lI2dcFCzvtdJbl1pYFa8xXldMu5oLGOwvQKnHnng
  pza492jHepwVjLeA8obqt2RZNHxIFLdOglVMcpGJTbcdgAbGh3CSuDpwP13N95ga
  7oxehfndKOD/LH941SVhUY7anesBzjC9QUpftIafh+dHb8vIGWCVjvc+OIaUIGSr
  t+fOujXGVCud084KKxojUvOSdOhgrWfUdoA1GqSrfq675TRYiLbAuoJeytCISB9V
  xUhbd/2WFSnXTVNGYn7t1Q8un16TLMU7OAr+XX0Y0zjU7Wsl1GMhLfx6UXKOde3N
  oVVE0WmfT/e4CS1h2AF2rhKCt9US/oi3mh8FEgZwulkZcBRXeWOdsn7EebS93NzC
  SWj4a/8XaBjg46XFUR3+rQkxEhDS9IDRa7WBN78I5X2Fw5Y/fPaXoaHxNIq6ayJj
  Q4CMX/BpDqVhJxHA6hkUTuhq9fesSSauPFE/HGadp9CABRUvTwFs1k03QYPCYyk9
  xznZNf49zniFrJvvT2QsDT6Nx3JAjeh7zI6ptgnm1ej7CbexCn/+/DbqokCNN7OU
  KlS5CqMdL+0da96soAxDRc9XMGWLlcNwQz0sqJJCoGSESzUkXZKRjgvHcNiT6TWg
  OF593Z0Eie2FpWEMo42Y50daXQLd3nl6nLTc3ruKeg6legkDAgMBAAGjgbwwgbkw
  HQYDVR0OBBYEFGd7PvxOCx8EmqkAsJSNGyKOPYnyMIGJBgNVHSMEgYEwf4AUZ3s+
  /E4LHwSaqQCwlI0bIo49ifKhZKRiMGAxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApD
  YWxpZm9ybmlhMRQwEgYDVQQHDAtTYW50YSBDbGFyYTETMBEGA1UECgwKQ29udHJv
  bGxlcjERMA8GA1UEAwwIY2EubG9jYWyCAQEwDAYDVR0TBAUwAwEB/zANBgkqhkiG
  9w0BAQsFAAOCAgEAHmKuecyQDUcXFBfLruXSxTsFeMN2/L8gQRBp3EN2WLU9aaoh
  ga8iUcaHNuiXUGbHY+Rhpkat7uJroM3FyuHqZJ5UcEUXdacPCCspyQt61o2UaqB1
  Be9qOW5bAbpWXjSKQgdMQHkHMiPTRqzZxB2OP3JF0jlf1QKro+Km5wBclcvofL24
  Wn/QaPW8nIJRwb9+9Y+ifq9CbmmNZTTCkjntk3lSU/YnKSI3/on7oPKCrQx3aKyF
  nr0YT0dJXsrcFxJ/vajFkzbX/V5Vhk7h6GTSh2E8KrUYdxqaucIhSxTgotV0iiiR
  QATK4flX0AG25aSCJdDWtNeGeUi/d28VijQs03smVIdFUfo5hRZPxbGsXtEbS1xz
  vP7hRAO/UtSiqaWBfAMIXx/zzpirqa88F4qdd8TKEQgLbI6prHR3NP2oIjOhpCeh
  909RRzkkxy2Qjsr5RrbBavVWxRZRvOaGnDUsC6I1JqkDp5MBlG55LAqA0D3gVeRC
  /+s99TB3l9eqjRtIbfGSSy2dAID/bWUFsty1BqdZg2M/Y0wYPNeuMx3yymfZZF1r
  u5ZuIDTOxrZ03laHB32L3meiTNZ1dXkwIyHkOGa/mm3yJVvcu+/9shfSulgpWbcr
  oxebqUHt4tIPl8vgpkGx1/vvycmkIpQq3lF98gSoSUWy8mlOMROqH3amGUo=
  -----END CERTIFICATE-----
